In [7]:
import pandas as pd
import numpy as np
import math

In [19]:
df = pd.read_csv("./SALib_Samples.txt", sep=" ", header=None)

In [20]:
df[9] = df[9].apply(lambda x: [.1, 1][math.floor(x)])

In [21]:
df

,0,1,2,3,4,5,6,7,8,9
0,0.027520,4985.488281,2.743164,2.474609,6.455078,0.853711,2.143555,1.072266,1.435547,0.1
1,1.370684,4985.488281,2.743164,2.474609,6.455078,0.853711,2.143555,1.072266,1.435547,0.1
2,0.027520,9980.488281,2.743164,2.474609,6.455078,0.853711,2.143555,1.072266,1.435547,0.1
3,0.027520,4985.488281,1.021680,2.474609,6.455078,0.853711,2.143555,1.072266,1.435547,0.1
4,0.027520,4985.488281,2.743164,2.611328,6.455078,0.853711,2.143555,1.072266,1.435547,0.1
...,...,...,...,...,...,...,...,...,...,...
5627,1.031973,8302.480469,0.336133,5.716797,1.833984,1.123242,3.848633,0.767578,4.521484,0.1
5628,1.031973,8302.480469,0.336133,5.716797,1.833984,1.123242,3.022461,1.388672,4.521484,0.1
5629,1.031973,8302.480469,0.336133,5.716797,1.833984,1.123242,3.022461,0.767578,1.103516,0.1
5630,1.031973,8302.480469,0.336133,5.716797,1.833984,1.123242,3.022461,0.767578,4.521484,0.1
5631,1.031973,8302.480469,0.336133,5.716797,1.833984,1.123242,3.022461,0.767578,4.521484,0.1

In [23]:
duplicates = df.duplicated()

In [26]:
df.loc[duplicates].sort_values(0)

,0,1,2,3,4,5,6,7,8,9
5620,0.015840,5024.511719,1.691992,5.228516,3.474609,1.238477,3.848633,1.388672,1.103516,0.1
10,0.027520,4985.488281,2.743164,2.474609,6.455078,0.853711,2.143555,1.072266,1.435547,0.1
2826,0.039199,1668.496094,3.611523,3.392578,1.888672,1.156445,2.758789,1.177734,1.611328,1.0
2804,0.050879,8341.503906,0.640820,5.560547,6.181641,0.951367,2.249023,0.861328,0.693359,1.0
4938,0.109277,341.699219,2.057617,1.634766,5.443359,0.879102,4.551758,2.982422,0.322266,1.0
...,...,...,...,...,...,...,...,...,...,...
3805,2.970801,7756.152344,0.244727,1.615234,6.482422,1.267773,4.534180,0.884766,1.044922,0.1
1891,2.982480,3034.316406,0.503711,2.806641,7.712891,1.195508,1.106445,1.576172,3.408203,0.1
3750,2.982480,4946.464844,3.550586,4.876953,3.310547,1.195508,2.688477,2.912109,3.095703,0.1
5103,2.994160,6741.542969,1.433008,4.310547,5.115234,0.982617,3.163086,0.111328,4.365234,0.1
1880,2.994160,5063.535156,0.701758,2.669922,6.509766,0.896680,3.303711,2.501953,4.677734,0.1